# Generated by Django 3.1.6 on 2021-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('cve_id', models.CharField(help_text='Unique ID for this particular CVE', max_length=255, primary_key=True, serialize=False)),
                ('today_occurrence_number', models.IntegerField(blank=True, default=None, null=True)),
                ('weekly_occurrence_number', models.IntegerField(default=None, null=True)),
                ('link', models.CharField(help_text='Link for getting further information on this particular CVE', max_length=255)),
            ],
        ),
    ]
