# Generated by Django 3.1.6 on 2021-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvegraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('last_retrieve_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
